# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5fa33e5c6c6f931b187c0ae1efa70a822d6f7ed2d7b4c9c34284124458ca112fc46f52c79bc1fee2e09838c26dcc1471215edd1d5e05d92ed543e5ce0b41ce6b

test:
  secret_key_base: d1e2c682dc4e7a25f1f370607b143f97d20d22a711ce8820c662b3390aac4cd19bcf3f06897d160133a678fedb78fc044101c380835d2efd5a122e5054919fab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
